Revert newline change, testing
Change-Id: Ic9d0d410a4174b1715fa736d252615590b9dc492

diff --git a/functions/main b/functions/main
--- a/functions/main
+++ b/functions/main
@@ -7,7 +7,7 @@
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 
 if ! [ -r "${FUNCTIONS}"/logs ] ; then
-  printf "Error: %s/logs could not be read. Exiting.\\n" "${FUNCTIONS}" >&2
+  printf "Error: %s/logs could not be read. Exiting.\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 # shellcheck disable=SC1090
diff --git a/scripts/check b/scripts/check
--- a/scripts/check
+++ b/scripts/check
@@ -10,7 +10,7 @@ FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 HELPER="${HELPER:-/usr/share/ngcp-ngcpcfg/helper/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}" >&2
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}" >&2
   exit 1
 fi
 
@@ -21,7 +21,7 @@ usage() {
   printf "ngcpcfg build -- supported command line options:
 
 --ignore-branch-check         - do not fail build if branch doesn't match 'master'
---ignore-shared-storage-check - skip check of shared storage\\n\\n"
+--ignore-shared-storage-check - skip check of shared storage\n\\n"
 }
 
 CHECK_BRANCH=true
diff --git a/scripts/services b/scripts/services
--- a/scripts/services
+++ b/scripts/services
@@ -15,7 +15,7 @@ CLEANUP_FILES=()
 # load modules
 
 if [[ ! -r "${FUNCTIONS}"/main ]]; then
-  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}">&2
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
diff --git a/scripts/status b/scripts/status
--- a/scripts/status
+++ b/scripts/status
@@ -10,7 +10,7 @@ set -o pipefail
 FUNCTIONS="${FUNCTIONS:-/usr/share/ngcp-ngcpcfg/functions/}"
 
 if ! [ -r "${FUNCTIONS}"/main ] ; then
-  printf "Error: %s/main could not be read. Exiting.\\n" "${FUNCTIONS}">&2
+  printf "Error: %s/main could not be read. Exiting.\n" "${FUNCTIONS}">&2
   exit 1
 fi
 
@@ -28,7 +28,7 @@ fi
 usage() {
   printf "ngcpcfg status -- supported command line options:
 
---local-only - do not check state on any remote host(s) (HA/PRO only)\\n\\n"
+--local-only - do not check state on any remote host(s) (HA/PRO only)\n\\n"
 }
 
 # shellcheck disable=SC2034
